In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((3, 2), dtype="int")

array([[0, 0],
       [0, 0],
       [0, 0]])

In [4]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
np.ones((3, 4, 5), dtype = "int")

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [6]:
np.full(2, 3, dtype = "int")

array([3, 3])

In [7]:
np.full((4, 3),12, dtype = "int")

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
example = np.arange(2, 11, 2, dtype = "int")
print(example)

[ 2  4  6  8 10]


In [10]:
"""
eye : 2 D array
"""
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
#Random numbers: rand function
np.random.rand(5)

array([0.54719886, 0.78902412, 0.73516569, 0.34876142, 0.7574237 ])

In [13]:
np.random.rand(2, 3)

array([[0.16638122, 0.28778604, 0.31057234],
       [0.75084031, 0.41174594, 0.31727077]])

In [14]:
np.random.randn(5) #randn fuction

array([-0.33849522, -1.23636197, -4.96563954,  1.11225835, -0.60620255])

In [15]:
import numpy as np
np.random.normal(20, 5, (4, 3)) #normal function

array([[16.1424229 , 14.47875796, 28.54386421],
       [19.35266223, 16.49090046, 12.58848844],
       [18.40469162, 20.8467149 , 12.09357655],
       [25.20220513, 20.31261207, 24.56444349]])

In [16]:
import numpy as np
matrix = np.random.randint(50, 98, (4, 5)) #randint function
print(matrix)

[[88 66 80 54 76]
 [75 63 74 59 77]
 [94 86 51 57 57]
 [55 55 65 55 52]]


In [17]:
matrix.ndim

2

In [18]:
matrix.shape
matrix.ndim
matrix.size

(4, 5)

In [19]:
matrix.size

20

In [20]:
import numpy as np
example = np.arange(1, 16)
example

array = example.reshape((3,5))
array

myarray = array.reshape((1, 15))
myarray

example.ndim
array.ndim
myarray.ndim

#largest element in an array of numpy
import numpy as np
array1 = np.random.randint(0, 100, 10)
array1

array1.max()
array1.argmax()
array2 = np.random.randint(0, 200, (4, 3))
array2
array2.max()
array2.argmax()
array1.min()
array1.argmin()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
array = example.reshape((3,5))
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
myarray = array.reshape((1, 15))
myarray

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [25]:
example.ndim

1

In [26]:
array.ndim

2

In [27]:
myarray.ndim

2

In [28]:
#largest element in an array of numpy
import numpy as np
array1 = np.random.randint(0, 100, 10)
array1

array([27, 34, 68, 82,  9,  4, 47, 13, 72, 93])

In [29]:
array1.max()

93

In [30]:
array1.argmax()

9

In [31]:
array2 = np.random.randint(0, 200, (4, 3))
array2

array([[ 65,  85, 123],
       [ 37,  23, 192],
       [117, 191,   1],
       [192,  22,  72]])

In [32]:
array2.max()

192

In [33]:
array2.argmax()

5

In [34]:
array1.min()

4

In [35]:
array1.argmin()

5

In [36]:
amb = np.array([1,2,3,4])
amb
amp = np.array([5,6,7,8])
amp
comb = np.concatenate([amb, amp])
comb
array3 = np.arange(1, 9).reshape(2,4)
array3
array4 = np.array([[1,2,3,4], [5,6,7,8]])
array4
array5 = np.concatenate([array3, array4])
array5
x, y = np.split(comb, 2)
#2dimension split, hsplit and vsplit vrs split
#np.sort(array)

array([1, 2, 3, 4])

In [37]:
amp = np.array([5,6,7,8])
amp

array([5, 6, 7, 8])

In [39]:
comb = np.concatenate([amb, amp])
comb

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
array3 = np.arange(1, 9).reshape(2,4)
array3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
array4 = np.array([[1,2,3,4], [5,6,7,8]])
array4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
array5 = np.concatenate([array3, array4])
array5

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
x, y = np.split(comb, 2)

In [53]:
x

array([1, 2, 3, 4])

In [54]:
y

array([5, 6, 7, 8])

In [ ]:
#2dimension split, hsplit and vsplit vrs split

In [ ]:
#np.sort(array)